version: '3.8'

services:
  mysql-master:
    build: ./master
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - master_data:/var/lib/mysql
    networks:
      - mysql-network

  mysql-slave:
    build: ./slave
    container_name: mysql-slave
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - slave_data:/var/lib/mysql
    networks:
      - mysql-network
    depends_on:
      - mysql-master

networks:
  mysql-network:
    driver: bridge

volumes:
  master_data:
  slave_data:
